on:
  push:
    branches: [ master ]
    paths: 
      - src/**
      
name: Create Release for master branch

jobs:
  createReleaseTag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Download XML Starlet
      run: sudo apt-get update; sudo apt-get install xmlstarlet -y
    - name: Determine current Version
      run: |
        currentVersion=$(xmlstarlet sel -t -v '//Version' src/SampleWebApi.csproj)
        echo "::set-env name=currentVersion::$currentVersion"
        echo "Current Version: $currentVersion"
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: v${{ env.currentVersion }}
        release_name: Version ${{ env.currentVersion }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
