on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  push:
    branches: [ master ]
    paths: 
      - src/**
      
name: Create Release for master branch

jobs:
  createReleaseTag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Download XML Starlet
      run: sudo apt-get update; sudo apt-get install xmlstarlet -y
    - name: Determine current Version
      run: |
        currentVersion=$(xmlstarlet sel -t -v '//Version' src/SampleWebApi.csproj)
        echo "::set-env name=currentVersion::$currentVersion"
        echo "Current Version: $currentVersion"
    
    
    - name: Git Message
      id: commitMessage
      # You may pin to the exact commit or the version.
      # uses: kceb/git-message-action@e6f4d4a48a0777818488be338da060d50933824e
      uses: kceb/git-message-action@v1    
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPOACCESSTOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: v${{ env.currentVersion }}
        release_name: Version ${{ env.currentVersion }}
        body: ${{ steps.commitMessage.outputs.git-message }}
        draft: false
        prerelease: false
