on:
  push:
    branches: [ master ]
    paths: 
      - src/**
      
name: Create Release Tag for master branch

jobs:
  createReleaseTag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Download XML Starlet
      run: sudo apt-get update; sudo apt-get install xmlstarlet -y
    - name: Determine current Version
      run: |
        currentVersion=$(xmlstarlet sel -t -v '//Version' src/SampleWebApi.csproj)
        echo "::set-env name=currentVersion::$currentVersion"
        echo "Current Version: $currentVersion"
    
    - name: Commit tagger
      uses: tvdias/github-tagger@v0.0.2
      with:
        # The GITHUB_TOKEN secret
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Tag text
        tag: v$(currentVersion)
        # optional commit sha to apply the tag to
        commit-sha: ${{ github.sha }}
